FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Coopersystem PHP

## Produto [/api/produto]

### Produto Listar [GET]

+ Response 200 (application/json)

        [
         {
            "id": 1,
            "nome": "Darron Nienow",
            "valorUnitario": "100",
            "quantidadeEstoque": "46",
            "situacao": "d",
            "created_at": "2019-07-02 20:31:45",
            "updated_at": "2019-07-02 20:34:38"
          },
          {
            "id": 2,
            "nome": "Golda Yost IV",
            "valorUnitario": "100",
            "quantidadeEstoque": "50",
            "situacao": "d",
            "created_at": "2019-07-02 20:31:45",
            "updated_at": "2019-07-02 20:31:45"
          },
        ]

### Produto Criar [POST]

+ Request (application/json)

        {
            "nome": "Carne",
            "valorUnitario": 100,
            "quantidadeEstoque": 100,
            "situacao": "d"
        }

+ Response 201 (application/json)

        {
            "message": "Sucesso!",
        }

## Produto [/api/produto/{id}]

### Detalhar [GET]

+ Response 200 (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

### Atualizar [PUT]

+ Request (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

+ Response 200 (application/json)

        {
            "message": "Sucesso!",
        }

### Excluir [DELETE]

+ Request (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

+ Response 200 (application/json)

        {
            "message": "Excluido!",
        }

## Pedido [/api/pedido]

### Pedido Listar [GET]

+ Response 200 (application/json)

        [
         {
            "id": 1,
            "nome": "Darron Nienow",
            "valorUnitario": "100",
            "quantidadeEstoque": "46",
            "situacao": "d",
            "created_at": "2019-07-02 20:31:45",
            "updated_at": "2019-07-02 20:34:38"
          },
          {
            "id": 2,
            "nome": "Golda Yost IV",
            "valorUnitario": "100",
            "quantidadeEstoque": "50",
            "situacao": "d",
            "created_at": "2019-07-02 20:31:45",
            "updated_at": "2019-07-02 20:31:45"
          },
        ]
        
### Pedido Criar [POST]

+ Request (application/json)

        {
            "nome": "Carne",
            "valorUnitario": 100,
            "quantidadeEstoque": 100,
            "situacao": "d"
        }

+ Response 201 (application/json)

        {
            "message": "Sucesso!",
        }

## Pedido [/api/pedido/{id}]

### Pedido Detalhar [GET]

+ Response 200 (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

### Pedido Atualizar [PUT]

+ Request (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

+ Response 200 (application/json)

        {
            "message": "Sucesso!",
        }

### Pedido Excluir [DELETE]

+ Request (application/json)

        {
            "nome": "Vegetal",
            "valorUnitario": 50,
            "quantidadeEstoque": 50,
            "situacao": "d"
        }

+ Response 200 (application/json)

        {
            "message": "Excluido!",
        }